### ISSUE TITLE
Remove Heroku integration code

### ISSUE THREAD

**Issue by nathan-weinberg** [transitmatters/regional-rail-explorer#42]
As we look to migrate to AWS, we might want to remove all off the various Heroku webhooks and such. cc @idreyn

**Comment by idreyn** [comment]
As far as code changes go, we'll be able to remove:

- The Heroku SSL middleware
- The `app.json` descriptor file

Both of these will be inert on the new instance, so we can do the handover and then remove them.

**Comment by nathan-weinberg** [comment]
cc @austinjpaul
