### ISSUE TITLE
Switch the `JourneySummaryCard` font from Helvetica to Liberation Sans

### ISSUE THREAD

**Issue by idreyn** [transitmatters/regional-rail-explorer#44]
The `JourneySummaryCard` component generates the social media previews for an RRX trip. It is rendered server-side and captured as a PNG. For this reason we need the fonts it uses on our server, and we have accomplished that using the questionably-legal [Helvetica Buildpack](https://github.com/rodley82/heroku-buildpack-helvetica-fonts). Before switching to AWS we'll need to make these changes:

- [ ] Include the free font [Liberation Sans](https://www.dafont.com/liberation-sans.font) in this repo
- [ ] Modify our CD system to copy it to the server
- [ ] Update `JourneySummaryCard.tsx` to swap out `Helvetica` for `Liberation Sans, Helvetica` (this can be tested locally)

**Comment by nathan-weinberg** [comment]
@idreyn Not sure exactly how we include the font in the repo, but if you can make that change I can make the CD change, then when we do the swap it should deploy onto the AWS instance

**Comment by idreyn** [comment]
It looks like Helvetica is actually working on [Preston's AWS instance](https://rre-beta.labs.transitmatters.org) (bless up) so no action is required here.
