### ISSUE TITLE
Identify Infill Stations

### ISSUE THREAD

**Issue by lawrencet1** [transitmatters/regional-rail-explorer#60]
There should be some kind of indicator for infill stations on the RRX. The reports use italics with a plus symbol. I'd be ok with just italics, but the plus symbol might help too, even if it's just text, eg _+ Alewife_, for example. 

Also, the RR side at the bottom should have a disclaimer when the new trip includes infills as well: 

> _This trip includes new infill stations as proposed by TransitMatters. Learn more in our reports. [Link]_

**Comment by idreyn** [comment]
Resolved in #62
